select * from customer limit 20

--Q1 - What is the total revenue generated by male vs. female customers?
SELECT "Gender",
       SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY "Gender";

--Q2 - Whcih customers used a discount but still spent more than the average purchase amount?
SELECT "Customer ID",
       "Purchase Amount (USD)"
FROM customer
WHERE "Discount Applied" = 'Yes'
  AND "Purchase Amount (USD)" >= (
      SELECT AVG("Purchase Amount (USD)")
      FROM customer
  );

--Q3 - Which are the top 5 products with the highest average review rating?
SELECT "Item Purchased",
       AVG("Review Rating") AS avg_review_rating
FROM customer
GROUP BY "Item Purchased"
ORDER BY avg_review_rating DESC
LIMIT 5;
--Q4 - Compare the average purchase amounts between Standard and Express Shipping ?
SELECT "Shipping Type",
       AVG("Purchase Amount (USD)") AS avg_purchase_amount
FROM customer
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type";
--Q5 - Do subscribed customers spend more? Compare average speed and total revenue between subscribers and non - subscribers?
SELECT "Subscription Status",
       AVG("Purchase Amount (USD)") AS avg_purchase_amount,
       SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Subscription Status";

--Q6 - Whicch 5 products have the highest percentage of purchases with discount applied?
SELECT "Item Purchased",
       COUNT(*) AS total_purchases,
       SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,
       ROUND(
           100.0 * SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
           2
       ) AS discount_percentage
FROM customer
GROUP BY "Item Purchased"
ORDER BY discount_percentage DESC
LIMIT 5;

--Q7 - Segment customers into New, Returning, and loyal based on their total number of previous purchases, and show the count of each segment.
SELECT customer_segment,
       COUNT(*) AS customer_count
FROM (
    SELECT CASE
        WHEN "Previous Purchases" = 1 THEN 'New'
        WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
    FROM customer
) AS segmented_customers
GROUP BY customer_segment
ORDER BY customer_count DESC;

--Q8 - What are the top 3 most purchased products within each category?
SELECT "Category",
       "Item Purchased",
       purchase_count
FROM (
    SELECT "Category",
           "Item Purchased",
           COUNT(*) AS purchase_count,
           RANK() OVER (
               PARTITION BY "Category"
               ORDER BY COUNT(*) DESC
           ) AS rank
    FROM customer
    GROUP BY "Category", "Item Purchased"
) AS ranked_products
WHERE rank <= 3
ORDER BY "Category", rank;

--Q9 - Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    CASE
        WHEN "Previous Purchases" > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS buyer_type,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN "Subscription Status" = 'Yes' THEN 1 ELSE 0 END) AS subscribed_customers,
    ROUND(
        100.0 * SUM(CASE WHEN "Subscription Status" = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS subscription_percentage
FROM customer
GROUP BY buyer_type;

--Q10 - What is the revenue contribution of each group ?
SELECT
    CASE
        WHEN "Age" BETWEEN 18 AND 25 THEN 'Young'
        WHEN "Age" BETWEEN 26 AND 40 THEN 'Adult'
        WHEN "Age" BETWEEN 41 AND 60 THEN 'Middle Aged'
        ELSE 'Senior'
    END AS age_group,
    SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;